#ifndef __lrabout__
#define __lrabout__

/**
@file
Subclass of LrAboutBase, which is generated by wxFormBuilder.
*/

#include "laterunui.h"

//// end generated include

/** Implementing LrAboutBase */
class LrAbout : public LrAboutBase
{
	protected:
		// Handlers for LrAboutBase events.

	public:
		/** Constructor */
		LrAbout( wxWindow* parent );
	//// end generated class members
	
};

#endif // __lrabout__
