#ifndef __lrexceptday__
#define __lrexceptday__

/**
@file
Subclass of LrExceptDayBase, which is generated by wxFormBuilder.
*/

#include "laterunui.h"

//// end generated include

class ExceptDayData;

/** Implementing LrExceptDayBase */
class LrExceptDay : public LrExceptDayBase
{
	public:
		/** Constructor */
		LrExceptDay( wxWindow* parent );

		//// end generated class members
	
		void SetExceptDay(const ExceptDayData& edData);
		void GetExceptDay(ExceptDayData& edData) const;

protected:
	virtual void OnBtnAddHolidayClick(wxCommandEvent& event) override;

	virtual void OnBtnDelHolidayClick(wxCommandEvent& event) override;

	virtual void OnBtnAddWorkdayClick(wxCommandEvent& event) override;

	virtual void OnBtnDelWorkdayClick(wxCommandEvent& event) override;

};

#endif // __lrexceptday__
